version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: server/docker/Dockerfile
    volumes:
    - "filesystem-volume:/usr/local/filesystem"
    ports:
    - "8080:8080"
    links:
    - "redis:db"
    - "rabbitmq:queue"
    depends_on:
    - redis
    - rabbitmq
    restart: "always"
  worker:
    build:
      context: .
      dockerfile: worker/docker/Dockerfile
    volumes:
    - "filesystem-volume:/usr/local/filesystem"
    links:
    - "redis:db"
    - "rabbitmq:queue"
    depends_on:
    - redis
    - rabbitmq
    restart: "always"
  redis:
    image: "redis"
    ports:
    - "6379:6379"
    restart: 'always'
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    - "5672:5672"
volumes:
  filesystem-volume:
