versions:
  - 0.0.1

server:
  environment: !env server_environment prod
  host: !env server_host 0.0.0.0
  port: !env server_port 8080

logging:
  level: !env log_level info
  dir: !env log_dir /usr/local/var/log/porta
  access-format: '"%r" %s %b %{X-Forwarded-For}i %{X-Trace-ID}i'
  config:
    version: 1
    disable_existing_loggers: false
    formatters:
      brief:
        format: "%(asctime)s %(message)s"
      simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(message)s"
  loggers:
    - aiohttp.access
    - aiohttp.server
    - aiohttp.application
    - aiohttp.general
    - aiohttp.client
  handler_defaults:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    maxBytes: 20000000
    backupCount: 7
    encoding: utf8

db:
  queue:
    backend: rabbitmq
    host: !env queue_host 127.0.0.1
    worker: !env queue_name task_queue
    app-key: queue
  file:
    backend: filesystem
    dir: !env storage_dir /Users/anmol.yadav/Documents/git/Thumbnailify/bin
    input-dir: !env input_dir raw
    app-key: filesystem

modules:
  - api.image
